name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '10' ]

    name: 'Build (.NET ${{matrix.dotnet-version}})'
    steps:
    - uses: actions/checkout@v6.0.1
    - uses: actions/setup-dotnet@v5.1.0
      with:
        dotnet-version: ${{matrix.dotnet-version}}
        dotnet-quality: 'ga'
    - run: dotnet restore
    - run: dotnet build --no-restore
