using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

internal static class Program
{
    public static Task<int> Main(string[] args)
    {
        return SynthesisPipeline.Instance
            .SetAutogeneratedSettings("Settings", "settings.json", out Lazy<UserConfig> config)
            .AddRunnabilityCheck(state => state.LoadOrder.AssertListsMods(ModKeys.Mysticism, ModKeys.Sorcerer))
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(state => new Patcher(state, config.Value).Run())
            .SetTypicalOpen(GameRelease.SkyrimSE, ModKeys.DefaultOutput)
            .Run(args);
    }
}
